const REVIEW_PROMPT = `
# PR Review

## Overview

Interactive comprehensive PR review focusing on critical issues: security vulnerabilities, performance degradation, and best practices. Generates concise, actionable comments.

Retrieve and review only the pull request diff.
If you identify an issue worth flagging, submit it back to GitHub only as an inline pull request review comment.
Do not submit an overall review state such as APPROVE, COMMENT, or REQUEST_CHANGES.


## Workflow

1. Authentication check

\`gh auth status\`

If not authenticated, guide user through \`gh auth login\`.

2. Fetch PR details

\`\`\`
# Get metadata
gh pr view {PULL_REQUEST_URL} --json title,body,state,author,files

# Get changed files list
gh pr view {PULL_REQUEST_URL} --json files --jq '.files[].path'

# Get full diff
gh pr diff {PULL_REQUEST_URL}
\`\`\`

3. Analyze pull request for potential comments

Analyze the pull request in an effort to find areas of improvement to comment on. The analysis should follow the following key areas:

### Focus areas

#### Security - priority: CRITICAL

- Ensure there are no security holes in the specified changes
- Follow any multi-tenancy best practices if appropriate
- Authentication/authorization bypasses
- Input validation/sanitization

#### Best practices - priority: MEDIUM

- Error handling
- Consistent code patterns (scoped by current project definitions)
- Code readability

4. Generate concise comments

Each comment should be short, concise and actionable. Refrain from asking questions in a comment, they should be direct changes that can be applied.

4.5. Confirm no duplicate comments

Fetch current comments on the PR:

\`\`\`
gh pr view {PULL_REQUEST_URL} --json comments --jq '.comments[] | {
  author: .author.login,
  createdAt: .createdAt,
  body: .body
}'
\`\`\`

Ensure there are no similar comments already existing on the PR. If there are similar comments already existing, discard the newly generated ones.

5. Manual selection

Present the list of comments to the user for selection (interactively), using AskUserQuestion or similar interactive tool.

**Example usage**:

\`\`\`
AskUserQuestion with questions:
[
  {
    "question": "Which CRITICAL concerns would you like to include in the final list of comments?",
    "header": "CRITICAL",
    "multiSelect": true,
    "options": [
      {
        "label": "No auth token sent in fetch request",
        "description": "The fetch request is completely open and does not include any auth token or header."
      }
    ]
  },
  {
    "question": "Which MEDIUM concerns would you like to include in the final list of comments?",
    "header": "MEDIUM",
    "multiSelect": true,
    "options": [
      {
        "label": "\`useEffect\` is not needed",
        "description": "\`isActive\` should use derived state instead of updating state within a \`useEffect\`."
      }
    ]
  }
]
\`\`\`

Before using AskUserQuestion, show a brief overview of the found concerns:

\`\`\`
I've completed my analysis and identified the following concerns:

## 🚨 CRITICAL ISSUES (2)
- Data Exfiltration Risk
- Missing Multi-tenant Isolation

## ⚡ HIGH PRIORITY (2)
- Blocking Operation
- Resource Leak

## ⚙️ MEDIUM PRIORITY (1)
- Error Handling Could Be More Specific

## ✅ STRENGTHS
- [Strength 1]
- [Strength 2]

Now let me present these interactively so you can select which to include in the final list of comments...
\`\`\`

6. Build structured comments

Comments should use proper GitHub Markdown Formatting. Each comment should follow the same structure:

Follow these key points:

- Use natural markdown syntax (no escaping)
- Use triple backticks for code blocks with language tags
- Use single backticks for inline code

Severity emojis:

- CRITICAL: 🚨
- HIGH: ⚠️
- MEDIUM: ⚙️
- LOW: 💡

\`\`\`
{severity_emoji} **{severity}: {title}**

**Issue:** {1-2 sentence problem description}

**Fix:**
{numbered actionable steps with cd examples}

---
🐶 Generated by Ody - the bestest of boys
\`\`\`

**Example formatted comment**:

\`\`\`
⚙️ **MEDIUM: \`useEffect\` is not needed**

**Issue:** \`isActive\` should use derived state instead of updating state within a \`useEffect\`.

**Fix:**
1. Derive \`isActive\` while rendering \`const isActive = !isLoading && actionIsAllowed\`.
2. Remove \`useEffect\` block on line 127.
3. Remove \`isActive\` \`setState\` definition from line 63.

---
🐶 Generated by Ody - the bestest of boys
\`\`\`

**IMPORTANT**: Always include the Ody attribution in the footer in every comment so developers know that the comment is AI-generated.

7. Post review comments

Use the GitHub CLI to post each inline comment to the pull request.

If any comments fail to post, be sure to collect each failed comment and then report those failed comments back to the user at the very end.

Once all comments are posted, report that the Pull Request review has been completed.
`;

export const buildReviewPrompt = ({ pullRequestUrl }: { pullRequestUrl: string }) =>
  REVIEW_PROMPT.replaceAll('{PULL_REQUEST_URL}', pullRequestUrl).trim();
